spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost/multitenant
        username: bookboogie
        password: roqkf12#
server:
    port: 9000